package main

import (
	"log"
	"net/http"
	"os"
	"yes-blog/graph"
	"yes-blog/graph/generated"
	controller "yes-blog/internal/controller/user"
	"yes-blog/pkg/database/mongodb"

	"github.com/99designs/gqlgen/graphql/handler"
	"github.com/99designs/gqlgen/graphql/playground"
)

const defaultPort = "8080"

func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = defaultPort
	}
	//_insertResult, _err := mongodb.GetClient().Database("yes-blog").Collection("users").InsertOne(context.TODO(), user.NewUser("ArshiA", "aliali"))
	//_insertResult=_insertResult
	//_err=_err

	//setting a mongodb.UserMongoDriver for UserDBDriver filed of our controller.GetUserController instance
	controller.GetUserController().SetDBDriver(mongodb.NewUserMongoDriver("yes-blog","users"))

	// generated by graphql
	srv := handler.NewDefaultServer(generated.NewExecutableSchema(generated.Config{Resolvers: &graph.Resolver{}}))

	http.Handle("/", playground.Handler("GraphQL playground", "/query"))
	http.Handle("/query", srv)

	log.Printf("connect to http://localhost:%s/ for GraphQL playground", port)
	log.Fatal(http.ListenAndServe(":"+port, nil))
}
