// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Post struct {
	ID        string `json:"id"`
	Auther    *User  `json:"auther"`
	Timestamp int    `json:"timestamp"`
	Body      string `json:"body"`
	Title     string `json:"title"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type TargetPost struct {
	Title string `json:"title"`
	Body  string `json:"body"`
}

type TargetUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type User struct {
	ID    string  `json:"id"`
	Name  string  `json:"name"`
	Posts []*Post `json:"posts"`
}
